const links=[...document.querySelectorAll('.nav-links a')];
const sections=[...document.querySelectorAll('section[id]')];
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id));}),{threshold:.45});
sections.forEach(s=>observer.observe(s));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'});}}));
const menu=document.querySelector('.menu-btn'), nav=document.querySelector('.nav-links');
menu?.addEventListener('click',()=>{nav.classList.toggle('mobile-open');});
links.forEach(a=>a.addEventListener('click',()=>nav.classList.remove('mobile-open')));
const glow=document.querySelector('.cursor-glow');
window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
